spring.application.name=jiin-backend
server.port=8080

# 실행 프로파일 (local, prod)
spring.profiles.active=local

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
