spring.application.name=jiin-backend
server.port=8080

# 실행 프로파일 (local, prod)
spring.profiles.active=local

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Swagger UI 접속 경로: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/api-docs
